SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE `delivery_order`
ADD COLUMN  `supply_id` BIGINT(11) UNSIGNED NULL,
ADD COLUMN  `checker_id` BIGINT(11) UNSIGNED NULL,
ADD COLUMN  `docloc` VARCHAR (25) NULL,
ADD  CONSTRAINT `fk_delivery_order_4`
FOREIGN KEY (`supply_id`)
REFERENCES `user` (`id`)
ON DELETE CASCADE
ON UPDATE NO ACTION,
ADD  CONSTRAINT `fk_delivery_order_5`
FOREIGN KEY (`checker_id`)
REFERENCES `user` (`id`)
ON DELETE CASCADE
ON UPDATE NO ACTION;